<a href="https://colab.research.google.com/github/anonymax25/tensorflow-jupyter-exo/blob/master/01_Introduction_a_tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction à TensorFlow : notions de base

Nous allons ici couvrir dans ce premier notebook les bases de TensorFlow et des tenseurs, éléments de base de TensorFlow :
- introduction aux tenseurs
- création et manipulation des tenseurs
- différence entre tenseurs et les tableaux numpy
- utilisation des GPUs avec TensorFlow

Lien vers la documentation officielle : https://www.tensorflow.org/api_docs/python/tf

## 1. Introduction aux tenseurs

### 1.1 Rappel

Vous pouvez voir le tenseur comme une représentation numérique à plusieurs dimensions (*n-dimensions*) de l'élément, la donnée que vous cherchez à représenter :
- une image (ex : tenseurs utilisés pour représenter les pixels de l'image)
- du texte (ex : tenseurs utilisés pour représenter des mots)
- directement des nombres (ex : tenseurs utilisés pour représenter le prix d'un bien immobilier)
- ou tout autre forme d'information (des données) que l'on veut représenter avec des nombres.

Les tenseurs sont équivalents aux tableaux NumPy (*NumPy arrays*) ; la différence majeure est que les tenseurs peuvent engendrer l'utilisation des GPUs (et TPUs si présents) (plus de détails dans le chapitre 3).

L'avantage de l'utilisation des GPUs (et TPUs) est que les calculs seront plus rapides.

### 1.2. Créer un tenseur avec `tf.constant()`

Nous devons d'abord importer TensorFlow (nous allons utiliser l'alias `tf` par la suite) :

In [3]:
import tensorflow as tf
print(tf.__version__)

2.5.0


En général, pour créer nos tenseurs, nous ne les créons pas nous-mêmes : nous utilisons les modules disponibles dans TensorFlow (par exemple `tf.io` ou `tf.data`).

Ces modules peuvent directement lire nos sources de données et automatiquement les convertir en tenseurs : les modèles de réseaux de neurones pourront ainsi par la suite les traiter.

Cependant, dans cette partie, afin de se familiariser avec les tenseurs, nous allons les créer par nous-mêmes et nous allons utiliser `tf.constant()` pour ce faire :

In [ ]:
scalaire = 
scalaire

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [ ]:
scalaire = tf.constant(6)
scalaire

<tf.Tensor: shape=(), dtype=int32, numpy=6>

Un scalaire peut être vu comme un tenseur de rang 0, parce qu'il n'a pas de dimension (c'est simplement un nombre). On peut vérifier la dimension d'un tenseur avec l'attribut `ndim` :

In [ ]:
# Dimension du tenseur


0

In [ ]:
scalaire.ndim

0

Créons maintenant un vecteur de dimension 1 :

In [ ]:
vecteur =
vecteur

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([6, 7, 8])>

In [ ]:
# Dimension du tenseur


1

In [ ]:
vecteur = tf.constant([6, 7, 8])
vecteur

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([6, 7, 8], dtype=int32)>

Même exercice pour une matrice (rang 2) :

In [ ]:
matrice =
matrice

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5,  6],
       [ 8, 10]])>

In [ ]:
# Dimension du tenseur


2

In [ ]:
matrice = tf.constant([[ 5,  6],
       [ 8, 10]])
matrice

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5,  6],
       [ 8, 10]], dtype=int32)>

Par défaut, TensorFlow crée des tenseurs de type `int32` ou `float32`.

Modifions le datatype par défaut (par exemple `float16`) en modifiant le paramètre `dtype` pour un nouveau tenseur de type matrice :

In [ ]:
matrice2 = tf.constant([[5., 1.],
       [3., 4.],
       [7., 9.]], "float16")
matrice2

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[5., 1.],
       [3., 4.],
       [7., 9.]], dtype=float16)>

In [ ]:
# Dimension du tenseur


2

In [ ]:
matrice2.ndim

2

Voici un autre exemple de tenseur, cette fois-ci de dimension 3 :

In [ ]:
tenseur = 
tenseur

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])>

In [ ]:
tenseur = tf.constant([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])
tenseur

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
# Dimension du tenseur


3

In [ ]:
tenseur.ndim

3

### 1.3. Créer un tenseur avec `tf.Variable()`

Nous pouvons également utiliser la fonction `tf.Variable()` pour créer un tenseur :

In [ ]:
tenseur_variable =
tenseur_non_modifiable =
tenseur_variable, tenseur_non_modifiable

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [ ]:
tenseur_variable = tf.Variable([10,  7])
tenseur_non_modifiable = tf.constant([10,  7])
tenseur_variable, tenseur_non_modifiable

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

La différence entre `tf.constant()` et `tf.Variable()` est que les tenseurs créés avec `tf.constant()` sont immuables (ils ne peuvent pas être modifiés) alors que les tenseurs créés avec `tf.Variable()` peuvent être modifiés.

Essayons justement de modifier un des éléments du tenseur modifiable :

In [ ]:
tenseur_variable [0] =
tenseur_variable

TypeError: 'ResourceVariable' object does not support item assignment

In [ ]:
tenseur_variable [0] = 1
tenseur_variable

TypeError: ignored

Oups ! On obtient une erreur !
Il faut passer par la méthode `assign()` pour pouvoir faire la modification souhaitée :

In [ ]:
tenseur_variable[0].
tenseur_variable

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 7])>

In [ ]:
tenseur_variable[0].assign(1)
tenseur_variable

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 7], dtype=int32)>

Nous pouvons vérifier que le tenseur créé à partir de `tf.constant()` ne peut pas être modifié :

In [ ]:
tenseur_non_modifiable[0] =

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

In [ ]:
tenseur_non_modifiable[0].

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

In [ ]:
tenseur_non_modifiable[0] = 2

TypeError: ignored

In [ ]:
tenseur_non_modifiable[0].assign(2)

AttributeError: ignored

### 1.4. Créer des tenseurs aléatoires

Les tenseurs aléatoires sont des tenseurs de taille aléatoire qui contiennent des nombres ... aléatoires !

Pourquoi vouloir créer de tels tenseurs ?

C'est en fait ce que les réseaux de neurones utilisent pour initialiser les *poids* (*weights* en anglais), les poids représentant le schéma que les réseaux de neurones essayent d'apprendre à partir des données.

Par exemple, le processus d'apprentissage d'un réseau de neurone consiste à :
- choisir un tableau aléatoire de nombres de n-dimensions
- puis d'affiner ce tableau jusqu'à ce qu'il représente une sorte de modèle, de schéma (*pattern*) (une manière compressée de représenter les données d'origine)

Créons des tenseurs aléatoires avec la classe `tf.random.Generator` (par exemple avec la "graine aléatoire" (*seed* ou *random seed* en anglais) égale à 42) :

In [ ]:
tf1 = 
tf2 = 

#choix d'une distribution normale et de dimension 3x2 pour nos deux tenseurs
tf1 = tf1.
tf2 = tf2.

Vérifions si nos deux tenseurs sont égaux :

In [ ]:
tf1, tf2, tf1 == tf2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [ ]:
tf1 = tf.random.Generator.from_seed(42)
tf2 = tf.random.Generator.from_seed(42)

#choix d'une distribution normale et de dimension 3x2 pour nos deux tenseurs
tf1 = tf1.normal(shape=(3, 2))
tf2 = tf2.normal(shape=(3, 2))

tf1, tf2, tf1 == tf2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

Du fait de l'utilisation d'un nombre (le paramètre de la méthode `from_seed()`), les tenseurs aléatoires que nous avons créés sont en en fait des nombres *pseudo-aléatoires* : on voit qu'en utilisant le même nombre, on obtient le même tenseur.

Voyons ce qu'il se passe si l'on change le paramètre d'entrée de la méthode `from_seed()` (par exemple pour la graine aléatoire égale à 10 pour le tenseur `tf4`) :

In [ ]:
tf3 = tf.
tf4 = tf.

#choix d'une distribution normale et de dimension 3x2 pour nos deux tenseurs
tf3 = tf3.
tf4 = tf4.

In [ ]:
tf3, tf4, tf1 == tf3, tf3 == tf4

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.29604465, -0.21134205],
        [ 0.01063002,  1.5165398 ],
        [ 0.27305737, -0.29925638]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

In [ ]:
tf3 = tf.random.Generator.from_seed(42)
tf4 = tf.random.Generator.from_seed(10)

#choix d'une distribution normale et de dimension 3x2 pour nos deux tenseurs
tf3 = tf3.normal(shape=(3, 2))
tf4 = tf4.normal(shape=(3, 2))

tf3, tf4, tf3 == tf4

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.29604465, -0.21134205],
        [ 0.01063002,  1.5165398 ],
        [ 0.27305737, -0.29925638]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

Maintenant, comment faire si l'on veut mélanger l'ordre des éléments d'un tenseur ?

D'abord, pourquoi voudrions-nous faire cela ?

Supposons que vous travaillez avec 1000 images de voitures et de vélos et que les 200 premières images sont celles représentant des voitures et les 800 dernières des motos. Cet ordre pourrait affecter la façon dont le réseau de neurones apprendra (il peut surajuster en apprenant l'ordre des données).

Cela peut ainsi être une bonne idée de mélanger les données avant d'entraîner notre modèle.

Voyons comme faire cela sur un exemple simple avec un tenseur de type constant :

In [ ]:
tenseur_non_melange = 
tenseur_non_melange

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  9],
       [ 8,  7],
       [ 6,  5]])>

In [ ]:
tenseur_non_melange = tf.constant([[10,  9],
       [ 8,  7],
       [ 6,  5]])
tenseur_non_melange

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  9],
       [ 8,  7],
       [ 6,  5]], dtype=int32)>

Mélangeons-le en utilisant la méthode `shuffle()` de la classe `random` :

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  9],
       [ 6,  5],
       [ 8,  7]])>

In [ ]:
tf.random.shuffle(tenseur_non_melange)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  9],
       [ 6,  5],
       [ 8,  7]], dtype=int32)>

On obtiendra à chaque essai un résultat différent.

Pour obtenir le même tenseur mélangé à chaque fois, on peut spécifier le paramètre `seed` (par exemple 42) :

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 6,  5],
       [ 8,  7],
       [10,  9]])>

In [ ]:
tf.random.shuffle(tenseur_non_melange, 42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 6,  5],
       [10,  9],
       [ 8,  7]], dtype=int32)>

En réalité, on n'obtient toujours pas le même tenseur mélangé ! On peut voir que l'ordre n'est pas toujours le même !

Pourquoi ? Cela est dû à la méthode `set_seed()` du module `tf.random` : `tf.random.set_seed(*nombre*)` spécifie le paramètre aléatoire (*seed*) au niveau global et le paramètre *seed* dans `tf.random.shuffle(seed=*nombre*)` le spécifie au niveau de l'opération effectuée (lien vers la règle 4 de la documentation de la méthode [set_seed()](https://www.tensorflow.org/api_docs/python/tf/random/set_seed)).

Si on spécifie le paramètre `seed` de la méthode `shuffle()`, il faut également spécifier le paramètre du niveau global pour pouvoir récupérer le même tenseur mélangé à chaque fois :

In [ ]:
tf.

tf.

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 6,  5],
       [ 8,  7],
       [10,  9]])>

In [ ]:
tf.random.set_seed(42)
tenseur_non_melange = tf.random.shuffle(tenseur_non_melange,seed=42)
tenseur_non_melange

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  9],
       [ 8,  7],
       [ 6,  5]], dtype=int32)>

On peut aussi seulement spécifier le niveau global :

In [ ]:
# en commentant la ligne ci-dessous, vous obtiendrez des résultats différents à chaque essai
tf.

tf.

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 6,  5],
       [10,  9],
       [ 8,  7]])>

In [ ]:
tf.random.set_seed(42)

tf.random.shuffle(tenseur_non_melange)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 8,  7],
       [ 6,  5],
       [10,  9]], dtype=int32)>

### 1.5. Autres façons de créer des tenseurs

On peut utiliser `tf.ones()` et `tf.zeros()` pour créer des tenseurs unitaires et nuls :

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [ ]:
tf.ones((4, 3), "float32")

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [ ]:
tf.zeros((4, 3), "float32")

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

Vous pouvez également convertir des tableaux `NumPy` en tenseurs (indication : la forme du tenseur (*shape*) doit correspondre au nombre d'éléments du tableau `NumPy`) :

In [ ]:
import numpy as np

array_A = np.
tenseur_T = tf.constant()

array_A, tenseur_T

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18]),
 <tf.Tensor: shape=(2, 3, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],
 
        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]])>)

In [ ]:
import numpy as np

array_A = np.array( [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18] )
tenseur_T = tf.constant(array_A,shape=(2,3,3))

array_A, tenseur_T

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18]), <tf.Tensor: shape=(2, 3, 3), dtype=int64, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],
 
        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]])>)

### 1.6. Informations relatives aux tenseurs

Nous pouvons accéder à plusieurs attributs des tenseurs nous informant sur :
- la forme : la taille de chaque dimension d'un tenseur
- le rang : le nombre de dimension du tenseur
- les dimensions
- la taille : le nombre d'éléments du tenseur

Ces informations peuvent être utiles lors des différentes étapes de notre calcul (par exemple, on peut vouloir s'assurer par exemple que les tenseurs de sortie sont de la même forme que les tenseurs en entrée).

Nous avons déjà vu l'attribut `ndim` qui nous donne la dimension du tenseur.

Nous allons maintenant voir l'attribut `shape` et la méthode `tf.size()`. Crééons un tenseur de dimension 4 :

In [ ]:
tenseur_4 = 
tenseur_4

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
tenseur_4 = tf.zeros((2, 3, 4, 5), "float32")
tenseur_4

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
tenseur_4., tenseur_4., tf.

(4, TensorShape([2, 3, 4, 5]), <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
tenseur_4.ndim, tenseur_4.shape, tf.size(tenseur_4)

(4, TensorShape([2, 3, 4, 5]), <tf.Tensor: shape=(), dtype=int32, numpy=120>)

On peut en fait accéder à différents attributs du tenseur :

In [ ]:
print("Datatype de chaque élement :", tenseur_4.)
print("Nombre de dimensions (rang) :", tenseur_4.)
print("Forme du tenseur:", tenseur_4.)
print("Elements sur l'axe 0 du tenseur :", tenseur_4.)
print("Elements sur le dernier axe du tenseur :", tenseur_4.)

# .numpy() permet de convertir en NumPy arrays
# on trouve bien (2*3*4*5) = 120
print("Nombre total d'éléments :", )

Datatype de chaque élement : <dtype: 'float32'>
Nombre de dimensions (rang) : 4
Forme du tenseur: (2, 3, 4, 5)
Elements sur l'axe 0 du tenseur : 2
Elements sur le dernier axe du tenseur : 5
Nombre total d'éléments : 120


In [ ]:
print("Datatype de chaque élement :", tenseur_4.dtype)
print("Nombre de dimensions (rang) :", tenseur_4.ndim)
print("Forme du tenseur:", tenseur_4.shape)
print("Elements sur l'axe 0 du tenseur :", tenseur_4.shape[0])
print("Elements sur le dernier axe du tenseur :", tenseur_4.shape[-1])

# .numpy() permet de convertir en NumPy arrays
# on trouve bien (2*3*4*5) = 120
print("Nombre total d'éléments :", tenseur_4.numpy().size)

Datatype de chaque élement : <dtype: 'float32'>
Nombre de dimensions (rang) : 4
Forme du tenseur: (2, 3, 4, 5)
Elements sur l'axe 0 du tenseur : 2
Elements sur le dernier axe du tenseur : 5
Nombre total d'éléments : 120


On peut utiliser l'indexation comme sur les listes :

In [ ]:
tenseur_4[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
tenseur_4[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
tenseur_4[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
tenseur_4[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
# récupérer le dernier élément par rapport au dernier axe
tenseur_4[]

<tf.Tensor: shape=(2, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
tenseur_4[:2,0,:4,:5]

<tf.Tensor: shape=(2, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

Nous pouvons également ajouter des dimensions à nos tenseurs, tout en gardant la même information en utilisant `tf.newaxis` :

In [ ]:
tenseur_2 = 
tenseur_2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[8, 5],
       [2, 6]])>

In [ ]:
tenseur_2 = tf.constant([[8, 5],
       [2, 6]])
tenseur_2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[8, 5],
       [2, 6]], dtype=int32)>

In [ ]:
tenseur_3 = tenseur_2[]
tenseur_3

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[8],
        [5]],

       [[2],
        [6]]])>

In [ ]:
tenseur_3 = tenseur_2[:, :, tf.newaxis]
tenseur_3

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[8],
        [5]],

       [[2],
        [6]]], dtype=int32)>

Vous pouvez également utiliser `tf.expand_dims()` pour le même résulat :

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[8],
        [5]],

       [[2],
        [6]]])>

In [ ]:
tf.expand_dims(tenseur_2, axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[8],
        [5]],

       [[2],
        [6]]], dtype=int32)>

`axis=-1` signifie le dernier axe.

## 2. Opérations des tenseurs

### 2.1. Opérations de base

Beaucoup des opérations mathématiques de base peuvent être réalisées directement sur les tenseurs en utilisant les opérateurs Python tel que `+`, `-`, `*` :

In [4]:
tenseur = 
tenseur

SyntaxError: ignored

In [10]:
tenseur = tf.constant([[8, 5],
       [2, 6]])
tenseur

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[8, 5],
       [2, 6]], dtype=int32)>

In [ ]:
# ajouter 10


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[18, 15],
       [12, 16]])>

In [11]:
tenseur = tenseur + 10
tenseur

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[18, 15],
       [12, 16]], dtype=int32)>

Puisque nous avons utilisé `tf.constant()`, le tenseur d'origine reste inchangé (l'addition est faite sur une copie du tenseur) :

In [ ]:
tenseur =

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[8, 5],
       [2, 6]])>

In [20]:
tenseur = tf.constant([[8, 5],
       [2, 6]])
tenseur

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[8, 5],
       [2, 6]], dtype=int32)>

Les opérations avec `-` et `*` fonctionnent de la même manière :

In [13]:
tenseur -= 10
tenseur

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-2, -5],
       [-8, -4]], dtype=int32)>

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[80, 50],
       [20, 60]])>

In [14]:
tenseur *= -10
tenseur

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 50],
       [80, 40]], dtype=int32)>

Vous pouvez également utiliser les fonctions TensorFlow équivalentes (quand elles sont disponibles), par exemple la fonction TensorFlow `multiply()` :

In [15]:
tf.multiply(tenseur, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[200, 500],
       [800, 400]], dtype=int32)>

Le tenseur d'origine reste aussi inchangé :

In [18]:
tenseur

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 50],
       [80, 40]], dtype=int32)>

### 2.2. Produit matriciel

Une des opérations les plus courantes en machine learning est la multiplication de matrices.

TensorFlow intègre la multiplication matricielle dans la méthode `tf.matmul()`.

Reprenons notre tenseur `tenseur` et appliquons le produit matriciel de ce tenseur par lui même avec la méthode `tf.matmul()` :

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[74, 70],
       [28, 46]])>

In [21]:
tf.matmul(tenseur,tenseur)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[74, 70],
       [28, 46]], dtype=int32)>

On obtient le même résultat avec l'opérateur Python `@` :

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[74, 70],
       [28, 46]])>

In [22]:
tenseur @ tenseur

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[74, 70],
       [28, 46]], dtype=int32)>

Cet exemple fonctionne car nous avons une matrice carrée.

Faisons par example le test avec deux tenseurs dont les dimensions ne sont pas compatibles pour un produit matriciel :

In [ ]:
X = 
Y = 
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]])>)

In [23]:
X = tf.constant([[1, 2],
        [3, 4],
        [5, 6]])
Y = tf.constant([[ 7,  8],
        [ 9, 10],
        [11, 12]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

InvalidArgumentError: Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul]

In [ ]:
tf.matmul(X, Y)

InvalidArgumentError: ignored

Le message d'erreur est assez explicite. Pour multiplier ces deux tenseurs, nous devons :
- soit modifier `X` pour avoir un tenseur de dimension `(2, 3)`
- soit remodeler `Y` pour avoir un tenseur de forme `(3, 2)`

Pour cela, deux méthodes peuvent être utilisées :
- `tf.reshape()` : la forme voulue doit être spécifiée
- `tf.transpose()` : comme avec les matrices, `transpose()` va permuter les dimensions du tenseur

Essayons d'abord `tf.reshape()`. Nous allons l'utiliser sur le tenseur `Y` et puis procéder au produit matriciel `@` avec `X` :

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]])>

In [26]:
tf.reshape(Y, (2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [ ]:
# produit matriciel


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]])>

In [31]:
X @ tf.reshape(Y, (2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

Essayons maintenant la méthode `tf.transpose()` sur `X` et `tf.matmul()` pour l'opérateur de multiplication matricielle :

In [ ]:
# transpose sur X


<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]])>

In [32]:
tf.transpose(X)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]], dtype=int32)>

In [ ]:
# multiplication matricielle


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]])>

In [44]:
tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

Nous pouvons obtenir le même résultat que ci-dessus en spécifiant le paramètre `transpose_a=True` :

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]])>

In [47]:
tf.matmul(X, Y, True)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

Vous pouvez également obtenir le même résultat que l'opération `tf.matmul()` avec `tf.tensordot()` :

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]])>

In [55]:
tf.tensordot(tf.transpose(X), Y, 2)

<tf.Tensor: shape=(), dtype=int32, numpy=212>

Pour les plus curieux, vous avez peut-être déjà vu que `reshape` et `transpose` donnaient des résultats différents.

Gardons les tenseurs `X` et `Y` et vérifions-cela :

In [ ]:
# multiplication avec l'utilisation de transpose sur Y


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]])>

In [ ]:
# multiplication avec l'utilisation de reshape sur Y


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]])>

Cela peut tout de même sembler bizarre parce que si l'on remodèle Y (avec `reshape`) ou que l'on permute `X` (`transpose`), on obtient dans les deux cas un tenseur de même forme :

In [ ]:
Y.shape, tf.reshape(Y, (2, 3)).shape, tf.transpose(Y).shape

(TensorShape([3, 2]), TensorShape([2, 3]), TensorShape([2, 3]))

En fait, nous pouvons facilement vérifier que `tf.reshape()` et `tf.transpose()` ne donnent pas les mêmes tenseurs :

In [ ]:
print("Tenseur Y d'origine :")
print(Y, "\n") # "\n" for newline

print("Y 'remodelé' sous la forme (2, 3) :")
print(tf.reshape(Y, (2, 3)), "\n")

print("Y 'transposé' :")
print(tf.transpose(Y))

Tenseur Y d'origine :
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y 'remodelé' sous la forme (2, 3) :
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y 'transposé' :
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


On comprend ainsi pourquoi nous obtenons plus haut des résultats différents pour nos deux produits matriciels.

### 2.3. Changer le type (datatype) d'un tenseur

Nous pouvons parfois vouloir modifier le datatype par défaut de notre tenseur.

C'est notamment le cas lorsque nous souhaitons faire nos calculs avec moins de précision (par exemple passer de variables de type `float 32-bit` au type `float 16-bit`).

Calculer avec une précision moindre est utile sur des équipements ayant moins de puissance de calcul, comme par exemple les appareils portables.

Vous pouvez changer le type d'un tenseur avec `tf.cast()` :

In [ ]:
# tenseur de type int32 par défaut
tenseur_A = 

# tenseur de type float32 par défaut
tenseur_B = 

tenseur_A, tenseur_B

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3])>,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([2.4, 3.8], dtype=float32)>)

In [59]:
# tenseur de type int32 par défaut
tenseur_A = tf.constant([2,3], "int32", (2,))

# tenseur de type float32 par défaut
tenseur_B = tf.constant([2.4, 3.8], "float32", (2,))

tenseur_A, tenseur_B

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([2.4, 3.8], dtype=float32)>)

In [ ]:
# modification du type de tenseur_B de float32 à float16
tenseur_B = tf.cast(tenseur_B, dtype=tf.float16)
tenseur_B

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([2.4, 3.8], dtype=float16)>

In [60]:
tenseur_B = tf.cast(tenseur_B, dtype=tf.float16)
tenseur_B

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([2.4, 3.8], dtype=float16)>

In [ ]:
# modification du type de tenseur_A de int32 à float32
tenseur_A = 
tenseur_A

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2., 3.], dtype=float32)>

In [61]:
tenseur_A = tf.cast(tenseur_A, dtype=tf.float32)
tenseur_A

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2., 3.], dtype=float32)>

### 2.4. Valeur absolue



Pour obtenir les valeurs absolues des éléments des tenseurs, nous pouvons utiliser `tf.abs()` :

In [ ]:
tenseur = 
tenseur

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -5, -10])>

In [64]:
tenseur = tf.constant([ -5, -10])
tenseur

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -5, -10], dtype=int32)>

In [ ]:
# valeur absolue


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 5, 10])>

In [65]:
tf.abs(tenseur)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 5, 10], dtype=int32)>

### 2.5. Min, max, moyenne, somme

Les tenseurs peuvent être rapidement agrégés (c'est-à-dire que l'on peut appliquer un calcul sur tout le tenseur) pour trouver des choses comme le minimum, le maximum, la moyenne et la somme de tous les éléments.

Les méthodes d'agrégation ont souvent la syntaxe `reduce_[action]()`, telles que :
- `tf.reduce_min()`
- `tf.reduce_max()`
- `tf.reduce_mean()`
- `tf.reduce_sum()`
- généralement, chacune de ces méthodes sont disponible dans le module `math`, par exemple `tf.math.reduce_min()` mais vous pouvez utiliser l'alias `tf.reduce_min()` .

Pour tester ces fonctions d'agrégation, nous allons créer un tenseur de 100 valeurs aléatoires choisies entre -50 et 50, à l'aide de la fonction `randint` du module `random` de NumPy :

In [ ]:
tenseur = 
tenseur

<tf.Tensor: shape=(100,), dtype=int32, numpy=
array([  4, -21, -28,  16,  32,  -9, -20,  12,   5,  11, -14,  35,  34,
        -6, -26,  30, -11, -27,  49, -41,  -8,  25,  22,  28,  -5,   8,
       -38, -10,  23,  38,  11,  19,  24,  25, -32, -33, -22, -37, -40,
        15,  33,  20,  45,  16,   8,  10,  40, -14, -34, -15,   6,  17,
       -45, -50,  49, -44,  25, -44,  -1,  40, -50,  49,   4,   8,  20,
       -23, -42,  -9,  46, -21,  21,  -4, -45,  13, -17,  -4, -35,  14,
        13,  23, -50, -32,  -9,  14,   0,  40,  18, -29, -41, -17,  12,
        14, -28, -43,  37,  -1,   6, -32, -47,  48])>

In [76]:
import numpy as np
tenseur = tf.constant(np.random.randint(-50, 50, 100, "int32"))
tenseur

<tf.Tensor: shape=(100,), dtype=int32, numpy=
array([-46, -47,  -2,  47,   7,  27,  33, -33,   7,  46,  27,  14,  -5,
        -5,   0, -25,  37, -44,  49,  12, -48,  -7, -17, -37, -19,  48,
       -20, -24,  15,  13,  13,  37,  -1,   4, -12,  45, -18, -49,  32,
       -39, -48,  30,  -4, -50,   1,  19,  15,  44, -11,  16,  44, -46,
        -4,  49,  34,  16,  47, -45, -45, -47,  40, -14,  43,  30,  42,
       -42,  -9,   1,  24, -12,  47,  23, -48,  21,  11, -34,  24, -15,
        21, -26, -42,  46, -31, -39,  36,  44, -43,   2,  -8,  -5,  31,
        48, -42, -24,   1,   7,  27, -10,  -3, -17], dtype=int32)>

In [ ]:
#min


<tf.Tensor: shape=(), dtype=int32, numpy=-50>

In [77]:
tf.reduce_min(tenseur)

<tf.Tensor: shape=(), dtype=int32, numpy=-50>

In [ ]:
#max


<tf.Tensor: shape=(), dtype=int32, numpy=49>

In [78]:
tf.reduce_max(tenseur)

<tf.Tensor: shape=(), dtype=int32, numpy=49>

In [ ]:
#moyenne


<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [79]:
tf.reduce_mean(tenseur)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [80]:
#somme


In [81]:
tf.reduce_sum(tenseur)

<tf.Tensor: shape=(), dtype=int32, numpy=135>

### 2.6. Trouver les positions maximum et minimum

Ceci peut être utile lorsque vous voulez aligner les probabilités de prédictions (par exemple `[0.92, 0.03, 0.05]`) avec vos étiquettes (par exemple `['Orange', 'Poire', 'Banane']`).

Ici, l'étiquette prédite (celle avec la plus grande probabilité) serait `Orange` .

Nous pouvons faire la même chose pour le minimum :
- `tf.argmax()` : trouve la position de l'élément maximum d'un tenseur donné
- `tf.argmin()` : trouve la position de l'élément minimum d'un tenseur donné

Crééons cette fois-ci un tenseur de 100 valeurs comprises entre 0 et 1 :

In [ ]:
tenseur = 
tenseur

<tf.Tensor: shape=(100,), dtype=float64, numpy=
array([0.43176854, 0.6583202 , 0.8700109 , 0.58817603, 0.22008158,
       0.35209401, 0.76621725, 0.52908204, 0.3021742 , 0.90459508,
       0.95778089, 0.76074908, 0.61938381, 0.02510168, 0.08979834,
       0.87966019, 0.16375411, 0.55181853, 0.77312096, 0.76015148,
       0.12793877, 0.81825676, 0.82063084, 0.41027661, 0.60035181,
       0.54739499, 0.7665225 , 0.89790361, 0.07929629, 0.56083205,
       0.04554573, 0.53382362, 0.09823263, 0.06457977, 0.87127352,
       0.5673915 , 0.81288638, 0.22707507, 0.74571628, 0.9178505 ,
       0.93886366, 0.41010078, 0.46371519, 0.30145872, 0.29934333,
       0.26781642, 0.21503381, 0.58581353, 0.66145385, 0.12710215,
       0.12533843, 0.06111898, 0.09861182, 0.69815358, 0.85906194,
       0.25390505, 0.08454181, 0.57618997, 0.05580406, 0.83523941,
       0.26637947, 0.42682472, 0.65868593, 0.44193388, 0.91181101,
       0.01254488, 0.9390497 , 0.23252546, 0.91442268, 0.47416644,
       0.96238

In [87]:
import numpy as np
tenseur = tf.constant(np.random.random(100), "float64")
tenseur

<tf.Tensor: shape=(100,), dtype=float64, numpy=
array([0.13619396, 0.68662567, 0.85210579, 0.66428239, 0.10083165,
       0.28222641, 0.0573474 , 0.43871799, 0.16579099, 0.60528097,
       0.43889998, 0.24776843, 0.04759674, 0.18763038, 0.29819134,
       0.19173086, 0.09231842, 0.94724775, 0.39964721, 0.21941207,
       0.90011493, 0.80133866, 0.56854898, 0.54297448, 0.07078954,
       0.66757181, 0.54950583, 0.33992864, 0.98695633, 0.23423595,
       0.5962581 , 0.21671092, 0.40001196, 0.15145129, 0.06231578,
       0.2737713 , 0.55205261, 0.3526004 , 0.9370059 , 0.11732856,
       0.10367919, 0.29028459, 0.7956425 , 0.5638379 , 0.2334701 ,
       0.12056207, 0.80910281, 0.25239123, 0.46641207, 0.85559679,
       0.96412437, 0.14146348, 0.76714397, 0.21412849, 0.1656685 ,
       0.59023797, 0.02120483, 0.54763528, 0.48301645, 0.93978085,
       0.24767429, 0.431601  , 0.94387334, 0.71075036, 0.15894802,
       0.72631239, 0.922912  , 0.32034267, 0.56508863, 0.28798001,
       0.71969

In [ ]:
#trouver la position de l'élément maximum


<tf.Tensor: shape=(), dtype=int64, numpy=73>

In [88]:
tf.argmax(tenseur)

<tf.Tensor: shape=(), dtype=int64, numpy=28>

In [ ]:
#trouver la position de l'élément minimum


<tf.Tensor: shape=(), dtype=int64, numpy=65>

In [90]:
tf.argmin(tenseur)

<tf.Tensor: shape=(), dtype=int64, numpy=96>

In [ ]:
print("La valeur maximale du tenseur est à la position : {}".format() 
print(f"La valeur maximale du tenseur est (avec tf.reduce_max) : {}") 
print(f"La valeur maximale du tenseur est (avec tf.argmax): {}")
print(f"Les 2 valeurs max sont-elles égales (elles devraient l'être) ? { == }")

La valeur maximale du tenseur est à la position : 73
La valeur maximale du tenseur est : 0.9741631681744679
La valeur maximale du tenseur est : 0.9741631681744679
Les 2 valeurs max sont-elles égales (elles devraient l'être) ? True


In [94]:
print(f"La valeur maximale du tenseur est à la position : {tf.argmax(tenseur)}")
print(f"La valeur maximale du tenseur est (avec tf.reduce_max) : {tf.reduce_max(tenseur)}") 
print(f"La valeur maximale du tenseur est (avec tf.argmax): {tenseur[tf.argmax(tenseur)]}")
print(f"Les 2 valeurs max sont-elles égales (elles devraient l'être) ? { tf.reduce_max(tenseur) == tenseur[tf.argmax(tenseur)]}")

La valeur maximale du tenseur est à la position : 28
La valeur maximale du tenseur est (avec tf.reduce_max) : 0.986956328239677
La valeur maximale du tenseur est (avec tf.argmax): 0.986956328239677
Les 2 valeurs max sont-elles égales (elles devraient l'être) ? True


### 2.7. "Restreindre" un tenseur (supprimer toutes les dimensions unitaires)

Si vous souhaitez supprimer les dimensions de taille 1, vous pouvez utiliser `tf.squeeze()` .

Prenons l'exemple d'un tenseur de forme `(1,1,20,1)` et de 20 valeurs aléatoires comprises entre 0 et 100 :

In [ ]:
tenseur = 
tenseur, tenseur.shape, tenseur.ndim

(<tf.Tensor: shape=(1, 1, 1, 20, 1), dtype=int32, numpy=
 array([[[[[77],
           [ 6],
           [62],
           [11],
           [77],
           [61],
           [88],
           [90],
           [38],
           [81],
           [55],
           [83],
           [27],
           [ 1],
           [40],
           [57],
           [29],
           [ 3],
           [64],
           [43]]]]])>,
 TensorShape([1, 1, 1, 20, 1]),
 5)

In [95]:
tenseur = tf.constant([[[[[77],
           [ 6],
           [62],
           [11],
           [77],
           [61],
           [88],
           [90],
           [38],
           [81],
           [55],
           [83],
           [27],
           [ 1],
           [40],
           [57],
           [29],
           [ 3],
           [64],
           [43]]]]])
tenseur, tenseur.shape, tenseur.ndim

(<tf.Tensor: shape=(1, 1, 1, 20, 1), dtype=int32, numpy=
 array([[[[[77],
           [ 6],
           [62],
           [11],
           [77],
           [61],
           [88],
           [90],
           [38],
           [81],
           [55],
           [83],
           [27],
           [ 1],
           [40],
           [57],
           [29],
           [ 3],
           [64],
           [43]]]]], dtype=int32)>, TensorShape([1, 1, 1, 20, 1]), 5)

In [ ]:
tenseur_restreint = tf.squeeze(tenseur)
tenseur_restreint, tenseur_restreint.shape, tenseur_restreint.ndim

(<tf.Tensor: shape=(20,), dtype=int32, numpy=
 array([77,  6, 62, 11, 77, 61, 88, 90, 38, 81, 55, 83, 27,  1, 40, 57, 29,
         3, 64, 43])>,
 TensorShape([20]),
 1)

In [96]:
tenseur_restreint = tf.squeeze(tenseur)
tenseur_restreint, tenseur_restreint.shape, tenseur_restreint.ndim

(<tf.Tensor: shape=(20,), dtype=int32, numpy=
 array([77,  6, 62, 11, 77, 61, 88, 90, 38, 81, 55, 83, 27,  1, 40, 57, 29,
         3, 64, 43], dtype=int32)>, TensorShape([20]), 1)

### 2.8. One-hot encoding

Si vous souhaitez transformer un tenseur d'indices en un tenseur "binaire" (chaque valeur d'indice aura sa modalité propre), vous pouvez utiliser `tf.one_hot()` .

Vous pourrez spécifier le paramètre `depth` (indique le niveau jusqu'où vous souhaitez encoder).

Testons cette fonction sur une liste triviale d'indices (avec `depth=4`) :

In [ ]:
ma_liste = [0, 1, 2, 3, 2]

# One hot encoding


<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.]], dtype=float32)>

In [97]:
ma_liste = [0, 1, 2, 3, 2]
tf.one_hot(ma_liste, 4)

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.]], dtype=float32)>

Vous pouvez aussi spécifier des valeurs pour les paramètres `on_value` et `off_value` au lieu des valeurs par défaut `1` et `0` :

In [99]:
ma_liste = [0, 1, 2, 3, 2]
tf.one_hot(ma_liste, 4, "oui", "non")

<tf.Tensor: shape=(5, 4), dtype=string, numpy=
array([[b'oui', b'non', b'non', b'non'],
       [b'non', b'oui', b'non', b'non'],
       [b'non', b'non', b'oui', b'non'],
       [b'non', b'non', b'non', b'oui'],
       [b'non', b'non', b'oui', b'non']], dtype=object)>

### 2.9. Autres fonctions utiles

Beaucoup d'autres fonctions mathématiques courantes existent également pour les tenseurs.

Nous allons par exemple regarder :
- `tf.square()` : calcule le carré de tous les éléments du tenseur
- `tf.sqrt()` : calcule la racine carré de tous les éléments du tenseur (les éléments du tenseur doivent être de type `float`)
- `tf.math.log()` : calcule le logarithme de tous les éléments du tenseur (les éléments du tenseur doivent ici aussi être de type `float`)

Nous allons créer un nouveau tenseur pour tester ces trois fonctions :

In [ ]:
tenseur = tf.constant(np.arange(1,20))
tenseur

<tf.Tensor: shape=(19,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])>

In [100]:
tenseur = tf.constant(np.arange(1,20))
tenseur

<tf.Tensor: shape=(19,), dtype=int64, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])>

In [ ]:
#carré


<tf.Tensor: shape=(19,), dtype=int32, numpy=
array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361])>

In [101]:
tf.square(tenseur)

<tf.Tensor: shape=(19,), dtype=int64, numpy=
array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361])>

In [ ]:
#racine carré


InvalidArgumentError: Value for attr 'T' of int32 is not in the list of allowed values: bfloat16, half, float, double, complex64, complex128
	; NodeDef: {{node Sqrt}}; Op<name=Sqrt; signature=x:T -> y:T; attr=T:type,allowed=[DT_BFLOAT16, DT_HALF, DT_FLOAT, DT_DOUBLE, DT_COMPLEX64, DT_COMPLEX128]> [Op:Sqrt]

Comme précisé plus haut, nous devons changer le datatype du tenseur pour pouvoir appliquer la fonction racine carré :

In [ ]:
tenseur = 
tenseur

<tf.Tensor: shape=(19,), dtype=float32, numpy=
array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19.], dtype=float32)>

In [106]:
tenseur = tf.cast(tenseur, "float32")
tenseur

<tf.Tensor: shape=(19,), dtype=float32, numpy=
array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19.], dtype=float32)>

In [ ]:
#racine carré


<tf.Tensor: shape=(19,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       , 3.162278 , 3.3166249, 3.4641016,
       3.6055512, 3.7416573, 3.8729832, 4.       , 4.1231055, 4.2426405,
       4.358899 ], dtype=float32)>

In [107]:
tf.sqrt(tenseur)

<tf.Tensor: shape=(19,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       , 3.162278 , 3.3166249, 3.4641016,
       3.6055512, 3.7416573, 3.8729832, 4.       , 4.1231055, 4.2426405,
       4.358899 ], dtype=float32)>

In [ ]:
#log


<tf.Tensor: shape=(19,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246, 2.3025851, 2.3978953, 2.4849067,
       2.5649493, 2.6390574, 2.7080503, 2.7725887, 2.8332133, 2.8903718,
       2.944439 ], dtype=float32)>

In [108]:
tf.math.log(tenseur)

<tf.Tensor: shape=(19,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246, 2.3025851, 2.3978953, 2.4849067,
       2.5649493, 2.6390574, 2.7080503, 2.7725887, 2.8332133, 2.8903718,
       2.944439 ], dtype=float32)>

### 2.10. Manipulation de tenseurs `tf.Variable`

Les tenseurs créés à partir de `tf.Variable()` peuvent être modifiés en utilisant des méthodes telles que :
- `.assign()` : affecte une valeur différente à un indice donné du tenseur variable
- `.assign_add()` : ajoute une valeur à la valeur existante pour un indice donné du tenseur variable

Faisons le test avec un tenseur, cette fois-ci variable :

In [ ]:
tenseur = 
tenseur

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([0, 1, 2, 3])>

In [109]:
tenseur = tf.Variable([0, 1, 2, 3]) 
tenseur

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([0, 1, 2, 3], dtype=int32)>

Nous allons modifier la valeur `2` à `10` :

<tf.Variable 'UnreadVariable' shape=(4,) dtype=int32, numpy=array([ 0,  1, 10,  3])>

In [112]:
tenseur[2].assign(10)

<tf.Variable 'UnreadVariable' shape=(4,) dtype=int32, numpy=array([ 0,  1, 10,  3], dtype=int32)>

On remarque que le tenseur est bien modifié :

In [ ]:
tenseur

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([ 0,  1, 10,  3])>

In [113]:
tenseur

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([ 0,  1, 10,  3], dtype=int32)>

Nous allons maintenant ajouter `25` pour les éléments du tenseur aux indices `1` et `3` :

<tf.Variable 'UnreadVariable' shape=(4,) dtype=int32, numpy=array([ 0, 26, 10, 28])>

In [115]:
tenseur[1].assign(tenseur[1] + 25)
tenseur[3].assign(tenseur[3] + 25)

<tf.Variable 'UnreadVariable' shape=(4,) dtype=int32, numpy=array([ 0, 26, 10, 28], dtype=int32)>

A nouveau, le tenseur est bien modifié :

In [ ]:
tenseur

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([ 0, 26, 10, 28])>

In [116]:
tenseur

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([ 0, 26, 10, 28], dtype=int32)>

## 3. Tenseurs et NumPy

Nous avons vu plus haut quelques exemples d'interaction entre les tenseurs et les tableaux NumPy (NumPy arrays), comme par exemple l'utilisation des NumPy arrays pour créer des tenseurs.

A l'inverse, les tenseurs peuvent également être convertis en NumPy arrays en utilisant :
- `np.array()` : convertit le tenseur en `ndarray` (datatype principal de NumPy)
- `tensor.numpy()` : méthode pour convertir le tenseur en `ndarray`

Cela est utile pour rendre les tenseurs itératifs, ainsi que pour pouvoir utiliser les méthodes `NumPy`.

Nous allons créer un tenseur de type constant à partir d'un tableau NumPy :

In [ ]:
A = 
A

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 2., -5.,  8.])>

In [117]:
A = tf.constant([ 2., -5.,  8.])
A

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([ 2., -5.,  8.], dtype=float32)>

In [ ]:
#conversion du tenseur A en NumPy ndarray avec np.array
, type()

(array([ 2., -5.,  8.]), numpy.ndarray)

In [122]:
np.array(A)

array([ 2., -5.,  8.], dtype=float32)

In [ ]:
#conversion du tenseur A en NumPy ndarray avec la méthode .numpy()
, type()

(array([ 2., -5.,  8.]), numpy.ndarray)

In [124]:
A.numpy()

array([ 2., -5.,  8.], dtype=float32)

Par défaut, les tenseurs ont le paramètre `dtype` égal à `float32`, alors que les tableaux NumPy ont `dtype=float64` .

Cela est dû au fait que les réseaux de neurones (qui sont généralement construits avec TensorFlow) fonctionnent généralement très bien avec moins de précision (32 bit au lieu de 64 bit) :

In [125]:
tenseur_A = tf.constant(np.array([1., 2., 3.])) # float64 (dû à NumPy)
tenseur_B = tf.constant([1., 2., 3.]) # float32 (valeur par défaut dans TensorFlow)
tenseur_A.dtype, tenseur_B.dtype

(tf.float64, tf.float32)

## 4. Tenseurs et GPUs

Nous avons mentionné à plusieurs reprises les GPUs dans ce notebook.

Mais comment vérifier si nous en avons un ?

Vous pouvez vérifier si vous avez accès à un GPU en utilisant `tf.config.list_physical_devices()` :

In [126]:
print(tf.config.list_physical_devices('GPU'))

[]


In [ ]:
print(tf.config.list_physical_devices('GPU'))

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


Si le résultat ci-dessus est vide, cela signifie que vous n'avez de GPU (ou que TensorFlow ne le trouve pas !).

Sous Google Colab vous pouvez accéder à un GPu en faisant *Runtime -> Change Runtime Type -> Select GPU* (**remarque:** après cette modification, le notebook redémarera et toutes les variables enregistrées seront perdues).

Vous pouvez également trouver les informations à propos de votre GPU avec `!nvidia-smi` :

In [131]:
!nvidia-smi

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



Si vous avez un GPU, TensorFlow l'utilisera automatiquement à chaque fois que cela est possible.